config/routes.rb
Igopal::Application.routes.draw do
  resources :organizations

  resources :achievements

  resources :users

  get "home/index"

  root :to=> "home#index"

end

app/models/achievement.rb
class Achievement < ActiveRecord::Base
  attr_accessible :end_date, :headline, :notes, :start_date, :work
  has_attached_file :work
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  attr_accessible :address, :city, :name, :state, :url, :user, :zip, :logo, :cover
    has_attached_file :logo
    has_attached_file :cover
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :login_name, :avatar
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController
  # GET /achievements
  # GET /achievements.json
  def create
    @achievement = Achievement.create( params[:achievement] )
end
  def index
    @achievements = Achievement.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @achievements }
    end
  end

  # GET /achievements/1
  # GET /achievements/1.json
  def show
    @achievement = Achievement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @achievement }
    end
  end

  # GET /achievements/new
  # GET /achievements/new.json
  def new
    @achievement = Achievement.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @achievement }
    end
  end

  # GET /achievements/1/edit
  def edit
    @achievement = Achievement.find(params[:id])
  end

  # POST /achievements
  # POST /achievements.json
  def create
    @achievement = Achievement.new(params[:achievement])

    respond_to do |format|
      if @achievement.save
        format.html { redirect_to @achievement, notice: 'Achievement was successfully created.' }
        format.json { render json: @achievement, status: :created, location: @achievement }
      else
        format.html { render action: "new" }
        format.json { render json: @achievement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /achievements/1
  # PUT /achievements/1.json
  def update
    @achievement = Achievement.find(params[:id])

    respond_to do |format|
      if @achievement.update_attributes(params[:achievement])
        format.html { redirect_to @achievement, notice: 'Achievement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @achievement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /achievements/1
  # DELETE /achievements/1.json
  def destroy
    @achievement = Achievement.find(params[:id])
    @achievement.destroy

    respond_to do |format|
      format.html { redirect_to achievements_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  # GET /organizations
  # GET /organizations.json
  def create
  @organization = Organization.create( params[:organization] )
end
  def index
    @organizations = Organization.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organizations }
    end
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @organization = Organization.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/new
  # GET /organizations/new.json
  def new
    @organization = Organization.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/1/edit
  def edit
    @organization = Organization.find(params[:id])
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(params[:organization])

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render json: @organization, status: :created, location: @organization }
      else
        format.html { render action: "new" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organizations/1
  # PUT /organizations/1.json
  def update
    @organization = Organization.find(params[:id])

    respond_to do |format|
      if @organization.update_attributes(params[:organization])
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy

    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
def create
  @user = User.create( params[:user] )
end

  
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/achievements_helper.rb
module AchievementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/achievements/_form.html.erb
<%= form_for(@achievement) do |f| %>
  <% if @achievement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@achievement.errors.count, "error") %> prohibited this achievement from being saved:</h2>

      <ul>
      <% @achievement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :headline %><br />
    <%= f.text_field :headline %>
  </div>
  <div class="field" >
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>
  <div class="field" >
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_field :notes %>
  </div>
  <%= form_for @achievement, :url => achievements_path, :html => { :multipart => true } do |form| %>
  <%= form.file_field :work %>
<% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/achievements/_work.html.erb
 <%= form_for @achievement, :url => achievements_path, :html => { :multipart => true } do |form| %>
  <%= form.file_field :work %>
<% end %>

app/views/achievements/edit.html.erb
<h1>Editing achievement</h1>

<%= render 'form' %>

<%= link_to 'Show', @achievement %> |
<%= link_to 'Back', achievements_path %>

app/views/achievements/index.html.erb
<div id="my-timeline"><h1><%= %>@Username Portfolio</h1></div>
<h3>Listing achievements</h3>

<% @achievements.each do |achievement| %>
<div class="achievement"
    <strong><%= achievement.headline %></strong>
    <p><%= achievement.start_date %> to 
    <%= achievement.end_date %></p>
    <em><%= achievement.notes %></em>
    <div class="meta">
      <%= link_to time_ago_in_words(achievement.created_at) + " ago", achievement %>  

        <span class="options" :visible = false>      
      <p><%= link_to 'Show', achievement %>|<%= link_to 'Edit', edit_achievement_path(achievement) %>|
        <%= link_to 'Destroy', achievement, method: :delete, data: { confirm: 'Are you sure you want to delete this entry?' } %>
      </p>
    <div class="btn-group">
      <button class="btn">Show</button>
      <button class="btn">Edit</button>
      <button class="btn">Delete</button>
    </div>
      </span>
    </div>
  </div>
<% end %>



<br />

<button><%= link_to 'New Achievement', new_achievement_path %></button>

app/views/achievements/new.html.erb
<h1>New achievement</h1>

<%= render 'form' %>

<%= link_to 'Back', achievements_path %>

app/views/achievements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Headline:</b>
  <%= @achievement.headline %>
</p>

<p>
  <b>Start date:</b>
  <%= @achievement.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @achievement.end_date %>
</p>

<p>
  <b>Notes:</b>
  <%= @achievement.notes %>
</p>


<%= link_to 'Edit', edit_achievement_path(@achievement) %> |
<%= link_to 'Back', achievements_path %>

app/views/home/index.html.erb
<h1>igopal</h1>
<p>This will be our landing page.</p>
    <div class="hero-unit">
    <h1>Heading</h1>
    <p>Tagline</p>
    <p>
    <a class="btn btn-primary btn-large">
    Learn more
    </a>
    </p>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Igopal</title>
  <%= stylesheet_link_tag  "application", "bootstrap", :media => "all" %>
  <%= javascript_include_tag "jquery-1.8.2.min" "storyjs-embed","timeline", "bootstrap", "application" %>

</head>
<body background-color = "#005580">

    <div class="navbar" class = "navbar-static-top" class="container">
	    <div class="navbar-inner">
	    <a class="brand" href="#">igopal</a>
		<ul class="nav">
			<li class ="active" clas = "nav"><a><%=link_to "All Users", users_path%></a>
			</li>
			<li class="active" class = "nav"><a><%=link_to "All Achievements", achievements_path%></a>
			</li>

		</ul>
	    </div>
    </div>




<%= yield %>

</body>
</html>

app/views/organizations/_cover.html.erb
<%= form_for @organization, :url => organizations_path, :html => { :multipart => true } do |form| %>
  <%= form.file_field :cover %>
<% end %>

app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!--<div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>-->
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organizations/_logo.html.erb
<%= form_for @organization, :url => organizations_path, :html => { :multipart => true } do |form| %>
  <%= form.file_field :logo %>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<h1>Listing organizations</h1>

<table>
  <tr>
    <th>User</th>
    <th>Name</th>
    <th>Address</th>
    <th>City</th>
    <th>State</th>
    <th>Zip</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @organizations.each do |organization| %>
  <tr>
    <td><%= organization.user %></td>
    <td><%= organization.name %></td>
    <td><%= organization.address %></td>
    <td><%= organization.city %></td>
    <td><%= organization.state %></td>
    <td><%= organization.zip %></td>
    <td><%= organization.url %></td>
    <td><%= link_to 'Show', organization %></td>
    <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
    <td><%= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Organization', new_organization_path %>

app/views/organizations/new.html.erb
<h1>New organization</h1>

<%= render 'form' %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @organization.user %>
</p>

<p>
  <b>Name:</b>
  <%= @organization.name %>
</p>

<p>
  <b>Address:</b>
  <%= @organization.address %>
</p>

<p>
  <b>City:</b>
  <%= @organization.city %>
</p>

<p>
  <b>State:</b>
  <%= @organization.state %>
</p>

<p>
  <b>Zip:</b>
  <%= @organization.zip %>
</p>

<p>
  <b>Url:</b>
  <%= @organization.url %>
</p>


<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>

app/views/users/_avatar.html.erb
<%= form_for @user, :url => users_path, :html => { :multipart => true } do |form| %>
  <%= form.file_field :avatar %>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :login_name %><br />
    <%= f.text_field :login_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= form_for @user, :url => users_path, :html => { :multipart => true } do |form| %>
  <%= form.file_field :avatar %>
<% end %>
<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Login name</th>
    <th>Email</th>
    <th>First name</th>
    <th>Last name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.login_name %></td>
    <td><%= user.email %></td>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>
<%= form_for @user, :url => users_path, :html => { :multipart => true } do |form| %>
  <%= form.file_field :avatar %>
<% end %>
<%= render 'form' %>


<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<%= image_tag @user.avatar.url %>
<%= image_tag @user.avatar.url(:medium) %>
<%= image_tag @user.avatar.url(:thumb) %>
<p>
  <b>Login name:</b>
  <%= @user.login_name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>